const CAT_PINNED = [
  { id: "beauty", name: "美女" },
  { id: "handsome", name: "帅哥" },
  { id: "anime", name: "漫画" },
];
const CAT_MORE = [
  { id: "all", name: "全部" },
  { id: "scenery", name: "风景" },
  { id: "star", name: "星空" },
  { id: "pet", name: "萌宠" },
  { id: "landmark", name: "地标" },
  { id: "car", name: "汽车" },
  { id: "mine", name: "我的" },
];
const CATS = CAT_PINNED.concat(CAT_MORE);

const IMAGES = [
  { id: "beauty1", name: "窗边", src: "assets/beauty-window.png", cat: "beauty" },
  { id: "beauty2", name: "银杏", src: "assets/beauty-autumn.png", cat: "beauty" },
  { id: "beauty3", name: "雨伞", src: "assets/beauty-rain.png", cat: "beauty" },
  { id: "beauty4", name: "书香", src: "assets/beauty-library.png", cat: "beauty" },
  { id: "beauty5", name: "海边", src: "assets/beauty-seaside.png", cat: "beauty" },
  { id: "beauty6", name: "灯影", src: "assets/beauty-lantern.png", cat: "beauty" },
  { id: "beauty7", name: "咖啡", src: "assets/beauty-cafe.png", cat: "beauty" },
  { id: "beauty8", name: "地铁", src: "assets/beauty-subway.png", cat: "beauty" },
  { id: "beauty9", name: "樱花", src: "assets/beauty-sakura.png", cat: "beauty" },
  { id: "beauty10", name: "天台", src: "assets/beauty-sunset.png", cat: "beauty" },
  { id: "beauty11", name: "单车", src: "assets/beauty-bike.png", cat: "beauty" },
  { id: "beauty12", name: "工位", src: "assets/beauty-office.png", cat: "beauty" },
  { id: "beauty13", name: "夜市", src: "assets/beauty-nightmarket.png", cat: "beauty" },
  { id: "beauty14", name: "湖畔", src: "assets/beauty-lake.png", cat: "beauty" },
  { id: "beauty15", name: "耳机", src: "assets/beauty-music.png", cat: "beauty" },
  { id: "beauty16", name: "花房", src: "assets/beauty-greenhouse.png", cat: "beauty" },
  { id: "beauty17", name: "雪衣", src: "assets/beauty-snow.png", cat: "beauty" },
  { id: "beauty18", name: "厨房", src: "assets/beauty-kitchen.png", cat: "beauty" },
  { id: "beauty19", name: "画室", src: "assets/beauty-studio.png", cat: "beauty" },
  { id: "beauty20", name: "桥边", src: "assets/beauty-bridge.png", cat: "beauty" },

  { id: "guy1", name: "巷口", src: "assets/handsome-street.png", cat: "handsome" },
  { id: "guy2", name: "窗前", src: "assets/handsome-window.png", cat: "handsome" },
  { id: "guy3", name: "校园", src: "assets/handsome-bike.png", cat: "handsome" },
  { id: "guy4", name: "天台", src: "assets/handsome-rooftop.png", cat: "handsome" },
  { id: "guy5", name: "花市", src: "assets/handsome-market.png", cat: "handsome" },
  { id: "guy6", name: "琴房", src: "assets/handsome-piano.png", cat: "handsome" },
  { id: "guy7", name: "咖啡", src: "assets/handsome-cafe.png", cat: "handsome" },
  { id: "guy8", name: "地铁", src: "assets/handsome-subway.png", cat: "handsome" },
  { id: "guy9", name: "球场", src: "assets/handsome-court.png", cat: "handsome" },
  { id: "guy10", name: "海边", src: "assets/handsome-sea.png", cat: "handsome" },
  { id: "guy11", name: "工位", src: "assets/handsome-office.png", cat: "handsome" },
  { id: "guy12", name: "夜跑", src: "assets/handsome-run.png", cat: "handsome" },
  { id: "guy13", name: "下厨", src: "assets/handsome-kitchen.png", cat: "handsome" },
  { id: "guy14", name: "书店", src: "assets/handsome-bookstore.png", cat: "handsome" },
  { id: "guy15", name: "机车", src: "assets/handsome-moto.png", cat: "handsome" },
  { id: "guy16", name: "雨巷", src: "assets/handsome-rain.png", cat: "handsome" },
  { id: "guy17", name: "登山", src: "assets/handsome-hike.png", cat: "handsome" },
  { id: "guy18", name: "画廊", src: "assets/handsome-gallery.png", cat: "handsome" },
  { id: "guy19", name: "唱片", src: "assets/handsome-vinyl.png", cat: "handsome" },
  { id: "guy20", name: "阳台", src: "assets/handsome-balcony.png", cat: "handsome" },

  { id: "anime1", name: "风之丘", src: "assets/anime-girl-field.png", cat: "anime" },
  { id: "anime2", name: "灯火巷", src: "assets/anime-night-town.png", cat: "anime" },
  { id: "anime3", name: "月台", src: "assets/anime-train.png", cat: "anime" },
  { id: "anime4", name: "夜祭", src: "assets/anime-festival.png", cat: "anime" },
  { id: "anime5", name: "雪社", src: "assets/anime-snow.png", cat: "anime" },
  { id: "anime6", name: "崖边", src: "assets/anime-sea.png", cat: "anime" },
  { id: "anime7", name: "校门", src: "assets/anime-school.png", cat: "anime" },
  { id: "anime8", name: "拉面", src: "assets/anime-ramen.png", cat: "anime" },
  { id: "anime9", name: "雨街", src: "assets/anime-rain-street.png", cat: "anime" },
  { id: "anime10", name: "神社", src: "assets/anime-shrine.png", cat: "anime" },
  { id: "anime11", name: "书馆", src: "assets/anime-library.png", cat: "anime" },
  { id: "anime12", name: "天台", src: "assets/anime-rooftop.png", cat: "anime" },
  { id: "anime13", name: "骑行", src: "assets/anime-cycle.png", cat: "anime" },
  { id: "anime14", name: "雪屋", src: "assets/anime-cabin.png", cat: "anime" },

  { id: "sea", name: "海暮", src: "assets/seaside-sunset.png", cat: "scenery" },
  { id: "cabin", name: "山中小屋", src: "assets/mountain-cabin.png", cat: "scenery" },
  { id: "sun", name: "向日葵", src: "assets/sunflowers.png", cat: "scenery" },
  { id: "city", name: "夜雨", src: "assets/rainy-city.png", cat: "scenery" },
  { id: "tea", name: "晨茶", src: "assets/tea-morning.png", cat: "scenery" },
  { id: "yard", name: "江南院", src: "assets/jiangnan-yard.png", cat: "scenery", exclusive: true },
  { id: "bamboo", name: "竹径", src: "assets/scenery-bamboo.png", cat: "scenery" },
  { id: "fall", name: "飞瀑", src: "assets/scenery-waterfall.png", cat: "scenery" },
  { id: "terrace", name: "梯田", src: "assets/scenery-terrace.png", cat: "scenery" },
  { id: "dune", name: "沙丘", src: "assets/scenery-desert.png", cat: "scenery" },
  { id: "autumn", name: "秋林", src: "assets/scenery-autumn.png", cat: "scenery" },
  { id: "peak", name: "雪峰", src: "assets/scenery-snowpeak.png", cat: "scenery" },
  { id: "lavender", name: "薰衣", src: "assets/scenery-lavender.png", cat: "scenery" },

  { id: "milky", name: "银河", src: "assets/stars-milkyway.png", cat: "star" },
  { id: "lake", name: "星湖", src: "assets/stars-lake.png", cat: "star" },
  { id: "stardesert", name: "沙星", src: "assets/stars-desert.png", cat: "star" },
  { id: "starsnow", name: "雪星", src: "assets/stars-snow.png", cat: "star" },

  { id: "cat", name: "窗台猫", src: "assets/orange-cat.png", cat: "pet" },
  { id: "corgi", name: "柯基", src: "assets/pet-corgi.png", cat: "pet" },
  { id: "husky", name: "哈士奇", src: "assets/pet-husky.png", cat: "pet" },
  { id: "rabbit", name: "灰兔", src: "assets/pet-rabbit.png", cat: "pet" },
  { id: "golden", name: "金毛", src: "assets/pet-golden.png", cat: "pet" },
  { id: "kitten", name: "白猫", src: "assets/pet-kitten.png", cat: "pet" },
  { id: "redpanda", name: "小熊猫", src: "assets/pet-redpanda.png", cat: "pet" },
  { id: "hedgehog", name: "刺猬", src: "assets/pet-hedgehog.png", cat: "pet" },

  { id: "lm-sh", name: "上海", src: "assets/landmark-shanghai.png", cat: "landmark" },
  { id: "lm-bj", name: "北京", src: "assets/landmark-beijing.png", cat: "landmark" },
  { id: "lm-gz", name: "广州", src: "assets/landmark-guangzhou.png", cat: "landmark" },
  { id: "lm-hz", name: "杭州", src: "assets/landmark-hangzhou.png", cat: "landmark" },
  { id: "lm-xa", name: "西安", src: "assets/landmark-xian.png", cat: "landmark" },
  { id: "lm-cd", name: "成都", src: "assets/landmark-chengdu.png", cat: "landmark" },
  { id: "lm-sz", name: "深圳", src: "assets/landmark-shenzhen.png", cat: "landmark" },
  { id: "lm-nj", name: "南京", src: "assets/landmark-nanjing.png", cat: "landmark" },
  { id: "lm-suzhou", name: "苏州", src: "assets/landmark-suzhou.png", cat: "landmark" },
  { id: "lm-cq", name: "重庆", src: "assets/landmark-chongqing.png", cat: "landmark" },
  { id: "lm-wh", name: "武汉", src: "assets/landmark-wuhan.png", cat: "landmark" },
  { id: "lm-gl", name: "桂林", src: "assets/landmark-guilin.png", cat: "landmark" },
  { id: "lm-ls", name: "拉萨", src: "assets/landmark-lhasa.png", cat: "landmark" },
  { id: "lm-hk", name: "香港", src: "assets/landmark-hongkong.png", cat: "landmark" },
  { id: "lm-tp", name: "台北", src: "assets/landmark-taipei.png", cat: "landmark" },
  { id: "lm-xm", name: "厦门", src: "assets/landmark-xiamen.png", cat: "landmark" },
  { id: "lm-qd", name: "青岛", src: "assets/landmark-qingdao.png", cat: "landmark" },
  { id: "lm-heb", name: "哈尔滨", src: "assets/landmark-harbin.png", cat: "landmark" },
  { id: "lm-mo", name: "澳门", src: "assets/landmark-macau.png", cat: "landmark" },
  { id: "lm-sy", name: "三亚", src: "assets/landmark-sanya.png", cat: "landmark" },

  { id: "car1", name: "红跑", src: "assets/car-red-sport.png", cat: "car" },
  { id: "car2", name: "夜轿", src: "assets/car-black-sedan.png", cat: "car" },
  { id: "car3", name: "山路", src: "assets/car-white-suv.png", cat: "car" },
  { id: "car4", name: "老爷车", src: "assets/car-vintage.png", cat: "car" },
  { id: "car5", name: "充电", src: "assets/car-silver-ev.png", cat: "car" },
  { id: "car6", name: "海风", src: "assets/car-yellow-open.png", cat: "car" },
  { id: "car7", name: "沙地", src: "assets/car-offroad.png", cat: "car" },
  { id: "car8", name: "霓虹", src: "assets/car-blue-night.png", cat: "car" },
  { id: "car9", name: "甲壳虫", src: "assets/car-green-classic.png", cat: "car" },
  { id: "car10", name: "皮卡", src: "assets/car-pickup.png", cat: "car" },
  { id: "car11", name: "小车", src: "assets/car-mini.png", cat: "car" },
  { id: "car12", name: "赛道", src: "assets/car-track.png", cat: "car" },
  { id: "car13", name: "雪地", src: "assets/car-snow.png", cat: "car" },
  { id: "car14", name: "橙跑", src: "assets/car-orange.png", cat: "car" },
  { id: "car15", name: "白轿", src: "assets/car-white-luxury.png", cat: "car" },
  { id: "car16", name: "房车", src: "assets/car-camper.png", cat: "car" },
  { id: "car17", name: "的士", src: "assets/car-red-taxi.png", cat: "car" },
  { id: "car18", name: "旅行车", src: "assets/car-grey-wagon.png", cat: "car" },
  { id: "car19", name: "柠檬", src: "assets/car-lime.png", cat: "car" },
  { id: "car20", name: "沙滩", src: "assets/car-beach-jeep.png", cat: "car" },
];
